name: Deploy dev
run-name: Build and deploy
on:
  push:
    branches:
      - dev

with:
  AFL_USER_EMAIL: ${{ vars.AFL_USER_EMAIL }}
  AFL_SERVER_PORT: ${{ vars.DEV_AFL_SERVER_PORT }}

jobs:
  build-and-deploy:
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'master'
      - uses: ./.gitea/workflows/rust.yml

