name: Deploy dev
run-name: Build and deploy
on:
  push:
    branches:
      - dev

with:
  AFL_USER_EMAIL: ${{ vars.AFL_USER_EMAIL }}
  AFL_SERVER_PORT: ${{ vars.DEV_AFL_SERVER_PORT }}

jobs:
  build-and-deploy:
    uses: ./.gitea/workflows/rust.yml

